fix: use facilitator_id instead of user_id in FacilitatorSkill query
BUG FIX: 500 Error!

ERROR:
AttributeError: type object 'FacilitatorSkill' has no attribute 'user_id'

ISSUE:
- FacilitatorSkill model uses 'facilitator_id' not 'user_id'
- Query was using wrong field name

BEFORE:
FacilitatorSkill.query.filter_by(user_id=fac.id, ...)  ❌

AFTER:
FacilitatorSkill.query.filter_by(facilitator_id=fac.id, ...)  ✅

DATABASE SCHEMA:
class FacilitatorSkill:
    facilitator_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    module_id = db.Column(db.Integer, db.ForeignKey('module.id'))
    skill_level = db.Column(db.Enum(SkillLevel))

NOW WORKS!